barbellgym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact_us/', include('contact.urls')),
    path('training/', include('training.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'barbellgym.views.error_404'
handler403 = 'barbellgym.views.error_403'
handler400 = 'barbellgym.views.error_400'

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

products/urls.py
""" Urls for products """

from django.urls import path
from . import views

urlpatterns = [
    path('', views.products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

checkout/models.py
"""
Models for creating orders at checkout
"""

import uuid

from django.db import models
from django.db.models import Sum
from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile

# models


class Order(models.Model):
    """
    Data populating orders
    """
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders')
    order_number = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default='')
    order_fulfilled = models.BooleanField(default=False)

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update total each time a line item is added
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """
    Data populating lineitems within an Order
    """
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems')
    product = models.ForeignKey(
        Product,
        null=False,
        blank=False,
        on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2,
        null=True,
        blank=True)  # XS, S, M, L, XL, XXL, XXXL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    id = models.BigAutoField(primary_key=True)
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=True, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    in_stock = models.BooleanField(default=True)

    def __str__(self):
        return self.name

products/forms.py
""" Product form """

from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):
    """
    Form for adding products
    """

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
""" Product app views """

from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from django.views.decorators.csrf import csrf_exempt

from .models import Product, Category
from .forms import ProductForm

# views


@csrf_exempt
def products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    search = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            search = request.GET['q']
            if not search:
                messages.error(
                    request, "Please enter search criteria to continue")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=search) | Q(description__icontains=search)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': search,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ A view to add a product to the site """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, you do not have permisson \
            to access this page.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Product successfully added!')
            return redirect(
                reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to add product, please ensure form is valid')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, you do not have permisson to access this page.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to update product. \
                Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ A view to delete a product """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, you do not have \
        permisson to access this page.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product successfully deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                <hr>
                <h2 class="title-class mb-4">Product Management</h2>
                <h5>Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-8 offset-2">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                <hr>
                <h2 class="title-class mb-4">Product Management</h2>
                <h5>Edit a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-8 offset-2">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit">Edit Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <!-- Title -->
    <div class="overlay-products"></div>
    <div class="container-fluid">
        <div class="row">
            <div class="col text-center mt-3 py-3">
                <h2 class="title-class">{{ product.name }}</h2>
                <hr class="w-50 mb-1">
            </div>
        </div>
        <!-- Product Info-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-8 offset-2 ">
                    <div class="image-container my-5">
                        {% if product.image %}
                            <a href="{{ product.image.url }}" target="_blank">
                                <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                        {% else %}
                            <a href="">
                                <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="product-details-container mb-5 mt-md-5">
                        <h4 class="lead mb-0 text-center font-weight-bold">£{{ product.price }}</h4>
                        {% if product.category %}
                            <h5 class="mb-0">
                                <a href="{% url 'products' %}?category={{ product.category.name }}">
                                    <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                </a>
                            </h5>
                        {% endif %}
                        {% if product.rating %}
                            <h5><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</h5>
                        {% else %}
                            <h5>No Rating</h5>
                        {% endif %}
                        {% if request.user.is_superuser %}
                            <h5 class="ml-3">
                                <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                                <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                            </h5>
                        {% endif %}
                        <h5 class="mt-3">{{ product.description }}</h5>
                        {% if product.in_stock %}
                            <form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-12">
                                        <h5><strong>Size:</strong></h5>
                                        <select class="form-control rounded-0 w-50 offset-3" name="product_size"
                                            id='id_product_size'>
                                            {% if product.category.friendly_name == "Legging Sets" %}
                                                <option value="s">S</option>
                                                <option value="m" selected>M</option>
                                                <option value="l">L</option>
                                            {% elif product.category.friendly_name == "Weightlifting Belts" %}
                                                <option value="s">S</option>
                                                <option value="m" selected>M</option>
                                                <option value="l">L</option>
                                            {% else %}
                                                <option value="xs">XS</option>
                                                <option value="s">S</option>
                                                <option value="m" selected>M</option>
                                                <option value="l">L</option>
                                                <option value="xl">XL</option>
                                                <option value="xxl">XXL</option>
                                                <option value="xxxl">XXXL</option>
                                            {% endif %}
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <h5 class="mt-3"><strong>Quantity:</strong></h5>
                                        <div class="form-group w-50 offset-3">
                                            <div class="input-group">
                                                <div class="input-group-prepend">
                                                    <button class="decrement-qty btn btn-black rounded-0"
                                                        data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                        <span class="icon">
                                                            <i class="fas fa-minus"></i>
                                                        </span>
                                                    </button>
                                                </div>
                                                <input class="form-control qty_input" type="number" name="quantity" value="1"
                                                    min="1" max="99" data-item_id="{{ product.id }}"
                                                    id="id_qty_{{ product.id }}">
                                                    <div class="input-group-append">
                                                        <button class="increment-qty btn btn-black rounded-0"
                                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                            <span class="icon">
                                                                <i class="fas fa-plus"></i>
                                                            </span>
                                                        </button>
                                                    </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12 mb-5">
                                        <a href="{% url 'products' %}" class="btn btn-black rounded-0 mt-5">
                                            <span class="icon">
                                                <i class="fas fa-chevron-left"></i>
                                            </span>
                                            <span class="text-uppercase">Back to all products</span>
                                        </a>
                                        <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5"
                                            value="Add to Bag">
                                    </div>
                                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                </div>
                            </form>
                        {% else %}
                            <div class="col-12 pb-5">
                            <h5 class="text-danger">This product is currently out of stock <i class="far fa-times-circle"></i></h5>
                            <a href="{% url 'products' %}" class="btn btn-black rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Back to all products</span>
                            </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_script.html' %}
{% endblock %}